### ISSUE TITLE
cli.exe missing

### ISSUE THREAD

**Issue by lorenzoferrante** [deep-man-yy/grabthenudes#1]
Hi, 
I have a problem. When running the app it says that the file cli.exe is missing from /Users/cli/ directory. How can I get that cli.exe file?

Thanks

**Comment by deep-man-yy** [comment]
You are getting very confused, this repository is only to show that the project "GrabTheNudes" is a SCAM. **You must not download it or pay for it**.

For the next one, please see what this repository is about, if you still have any doubts, visit: https://github.com/deep-man-yy/grabthenudes/blob/master/README.md

**Comment by lorenzoferrante** [comment]
Ok you can delete the issue if you want. Thanks
